services:
  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - uds-socket:/socket:rw  # <-- ADICIONADO
    ports:
      - "9999:80"
    depends_on:
      - pod1
      - pod2
      - pod3
      - pod4
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "50MB"
  pod1: &pod
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    pull_policy: always
    container_name: pod1
    environment:
      - SOCKET_PATH=/socket/pod1.sock  # <-- ADICIONADO
    depends_on:
      - db
      - worker
    networks:
      - backend
    volumes:
      - uds-socket:/socket:rw  # <-- ADICIONADO
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "25MB"
  pod2:
    <<: *pod
    container_name: pod2
    environment:
      - SOCKET_PATH=/socket/pod2.sock
  pod3:
    <<: *pod
    container_name: pod3
    environment:
      - SOCKET_PATH=/socket/pod3.sock
  pod4:
    <<: *pod
    container_name: pod4
    environment:
      - SOCKET_PATH=/socket/pod4.sock
  db:
    build:
      context: .
      dockerfile: Dockerfile
      target: db
    pull_policy: always
    container_name: db
    networks:
      - backend
    volumes:
      - uds-socket:/socket
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "100MB"
  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    pull_policy: always
    container_name: worker
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - uds-socket:/socket
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "100MB"
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
volumes:
  uds-socket: